web/router.ex
defmodule MoneyTracker.Router do
  use MoneyTracker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug MoneyTracker.Plug.CurrentUserProvider
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MoneyTracker do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index

    get "/sign_in", SessionController, :index
    post "/sign_in", SessionController, :create
    delete "/sign_out", SessionController, :delete

    get "/transactions", TransactionController, :index

    resources "/places", PlaceController do
      resources "/transactions", PlaceTransactionController , as: :transaction
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MoneyTracker do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule MoneyTracker.LayoutView do
  @moduledoc """
  View model for the Layout
  """

  use MoneyTracker.Web, :view

  @doc """
  Specifies if dashboard link in the header active or not
  """
  @spec dashboard_link_active?(Plug.Conn.t) :: boolean
  def dashboard_link_active?(conn) do
    conn.request_path == "/"
  end

  @doc """
  Specifies if places link in the header active or not
  """
  @spec place_link_active?(Plug.Conn.t) :: boolean
  def place_link_active?(conn) do
    Regex.match? ~r/\/places(\/?(\d+)?\/?(\?.*)?)$/, conn.request_path
  end

  @doc """
  Specifies if transactions link in the header active or not
  """
  @spec transactions_link_active?(Plug.Conn.t) :: boolean
  def transactions_link_active?(conn) do
    Regex.match? ~r/^\/transactions(\/?(\d+)?\/?(\?.*)?)$/, conn.request_path
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MoneyTracker!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="/">
                <img alt="Brand" src="/images/logo.png" height="20">
              </a>
              <a class="navbar-brand" href="/">
                Money Tracker
              </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="<%= if dashboard_link_active?(@conn), do: "active" %>"><a href="/">Dashboard <span class="sr-only">(current)</span></a></li>
                <li class="<%= if place_link_active?(@conn), do: "active" %>"><a href="<%= place_path(@conn, :index) %>">Places <span class="sr-only">(current)</span></a></li>
                <li class="<%= if transactions_link_active?(@conn), do: "active" %>"><a href="<%= transaction_path(@conn, :index) %>">All Transactions <span class="sr-only">(current)</span></a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <%= if authenticated?(@conn) do %>
                  <p class="navbar-text"><%= raw "Hello, <b>#{@current_user.username}</b>!" %></p>
                  <li>
                    <%= button "Sign Out", to: session_path(@conn, :delete), method: :delete, class: "btn btn-danger navbar-btn" %>
                  </li>
                <% else %>
                  <li><a href="<%= session_path(@conn, :index) %>">Sign In</a></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>