web/router.ex
defmodule MoneyTracker.Router do
  use MoneyTracker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug MoneyTracker.Plug.CurrentUserProvider
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MoneyTracker do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index

    get "/sign_in", SessionController, :index
    post "/sign_in", SessionController, :create
    delete "/sign_out", SessionController, :delete

    get "/transactions", TransactionController, :index

    resources "/places", PlaceController do
      resources "/transactions", PlaceTransactionController , as: :transaction
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MoneyTracker do
  #   pipe_through :api
  # end
end

lib/money_tracker/place/balance_calculator.ex
defmodule MoneyTracker.Place.BalanceCalculator do
  @moduledoc """
  Provides functionality to calculate current balance of a given place or several places.
  """

  alias MoneyTracker.{Place, Transaction, Repo}

  @doc """
  Runs calculator.
  """
  @spec run(Place.t | [Place.t]) :: float
  def run(%Place{} = place) do
    Transaction
    |> Transaction.for_place(place)
    |> Repo.all
    |> Enum.reduce(0.0, fn(transaction, acc) -> acc + transaction.amount end)
  end
  def run(places) when is_list(places) do
    Transaction
    |> Transaction.for_places(places)
    |> Repo.all
    |> Enum.reduce(0.0, fn(transaction, acc) -> acc + transaction.amount end)
  end
end

web/models/place.ex
defmodule MoneyTracker.Place do
  @moduledoc """
  Represents a Money Place entity in the system
  """

  use MoneyTracker.Web, :model

  alias MoneyTracker.User

  schema "places" do
    field :currency, :string
    field :title, :string
    field :description, :string

    belongs_to :user, MoneyTracker.User
    has_many :transactions, MoneyTracker.Transaction

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:currency, :title, :description, :user_id])
    |> validate_required([:currency, :title, :description, :user_id])
  end

  @doc """
  Scope to filter places by user
  """
  @spec for_user(Ecto.Queryable.t, User.t) :: Ecto.Queryable.t
  def for_user(query, %User{} = user) do
    from p in query,
    where: p.user_id == ^user.id
  end

  @doc """
  Scope to filter places by currency
  """
  @spec for_currency(Ecto.Queryable.t, String.t) :: Ecto.Queryable.t
  def for_currency(query, currency) do
    from p in query,
    where: p.currency == ^currency
  end
end

web/controllers/place_controller.ex
defmodule MoneyTracker.PlaceController do
  use MoneyTracker.Web, :controller

  alias MoneyTracker.Place

  plug Guardian.Plug.EnsureAuthenticated, handler: __MODULE__

  def index(conn, _params) do
    user = conn.assigns[:current_user]
    places = Place |> Place.for_user(user) |> Repo.all
    render(conn, "index.html", places: places)
  end

  def new(conn, _params) do
    changeset = Place.changeset(%Place{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"place" => place_params}) do
    user = conn.assigns[:current_user]
    changeset = %Place{user_id: user.id}
                |> Place.changeset(place_params)

    case Repo.insert(changeset) do
      {:ok, _place} ->
        conn
        |> put_flash(:info, "Place created successfully.")
        |> redirect(to: place_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = conn.assigns[:current_user]
    place = fetch_place(user, id)
    render(conn, "show.html", place: place)
  end

  def edit(conn, %{"id" => id}) do
    user = conn.assigns[:current_user]
    place = fetch_place(user, id)
    changeset = Place.changeset(place)
    render(conn, "edit.html", place: place, changeset: changeset)
  end

  def update(conn, %{"id" => id, "place" => place_params}) do
    user = conn.assigns[:current_user]
    place = fetch_place(user, id)
    changeset = Place.changeset(place, place_params)

    case Repo.update(changeset) do
      {:ok, place} ->
        conn
        |> put_flash(:info, "Place updated successfully.")
        |> redirect(to: place_path(conn, :show, place))
      {:error, changeset} ->
        render(conn, "edit.html", place: place, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = conn.assigns[:current_user]
    place = fetch_place(user, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(place)

    conn
    |> put_flash(:info, "Place deleted successfully.")
    |> redirect(to: place_path(conn, :index))
  end

  def unauthenticated(conn, _params) do
    conn
    |> put_flash(:error, "You must to authenticate first to see this page!")
    |> redirect(to: session_path(conn, :index))
  end

  defp fetch_place(user, place_id) do
    Place
    |> Place.for_user(user)
    |> Repo.get!(place_id)
  end
end

web/views/place_view.ex
defmodule MoneyTracker.PlaceView do
  @moduledoc """
  View model for the Place entity
  """

  use MoneyTracker.Web, :view

  alias MoneyTracker.Place
  alias Place.BalanceCalculator

  @doc """
  Returns a balance for a given place
  """
  @spec place_balance(Place.t) :: float
  def place_balance(place) do
    place
    |> BalanceCalculator.run
    |> number_to_currency(decimals: 2, unit: place.currency)
  end
end

web/templates/place/edit.html.eex
<h2>Edit place</h2>

<%= render "form.html", changeset: @changeset,
                        action: place_path(@conn, :update, @place) %>

<%= link "Back", to: place_path(@conn, :index) %>

web/templates/place/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :currency, class: "control-label" %>
    <%= text_input f, :currency, class: "form-control" %>
    <%= error_tag f, :currency %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= text_input f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/place/index.html.eex
<h2>Listing places</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Balance</th>
      <th>Currency</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for place <- @places do %>
    <tr>
      <td><%= place.title %></td>
      <td><%= place.description %></td>
      <td><%= place_balance(place) %></td>
      <td><%= place.currency %></td>

      <td class="text-right">
        <%= link "Show", to: place_path(@conn, :show, place), class: "btn btn-default btn-xs" %>
        <%= link "Transactions", to: place_transaction_path(@conn, :index, place), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: place_path(@conn, :edit, place), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: place_path(@conn, :delete, place), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New place", to: place_path(@conn, :new) %>

web/templates/place/new.html.eex
<h2>New place</h2>

<%= render "form.html", changeset: @changeset,
                        action: place_path(@conn, :create) %>

<%= link "Back", to: place_path(@conn, :index) %>

web/templates/place/show.html.eex
<h2>Show place</h2>

<ul>


  <li>
    <strong>Title:</strong>
    <%= @place.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @place.description %>
  </li>

  <li>
    <strong>Currency:</strong>
    <%= @place.currency %>
  </li>

  <li>
    <strong>Current Balance:</strong>
    <%= place_balance(@place) %>
  </li>

</ul>

<%= link "Edit", to: place_path(@conn, :edit, @place) %>
&nbsp;|&nbsp;
<%= link "Back", to: place_path(@conn, :index) %>
&nbsp;|&nbsp;
<%= link "Transactions", to: place_transaction_path(@conn, :index, @place) %>